CREATE TABLE IF NOT EXISTS public.conta
(
    dtype      character varying(31) NOT NULL,
    id_conta   bigint                NOT NULL,
    balance    numeric(10, 2),
    titular    character varying(255),
    emprestimo numeric(38, 2),
    CONSTRAINT conta_dtype_check CHECK (((dtype)::text = ANY
                                         ((ARRAY ['ContaCorrente'::character varying, 'ContaEmpresarial'::character varying, 'ContaPoupanca'::character varying])::text[])))
);

CREATE SEQUENCE IF NOT EXISTS public.conta_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS public.transacao
(
    id            bigint NOT NULL,
    data          timestamp(6) with time zone,
    saldo_apos    numeric(10, 2),
    tipo_operacao character varying(255),
    valor         numeric(10, 2),
    id_conta      bigint,
    CONSTRAINT transacao_tipo_operacao_check CHECK (((tipo_operacao)::text = ANY
                                                     ((ARRAY ['OPERACAO_DEPOSITO'::character varying, 'OPERACAO_SAQUE'::character varying, 'OPERACAO_TRANSFERENCIA'::character varying])::text[])))
);

ALTER TABLE public.transacao
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.transacao_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE ONLY public.conta
    ADD CONSTRAINT conta_pkey PRIMARY KEY (id_conta);
ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT fkj57iekb2ucoyifb1flof7kjml FOREIGN KEY (id_conta) REFERENCES public.conta (id_conta);