--
-- PostgreSQL database dump
--

\restrict NL08lT4EKcPwTh2UqrsxVOGDrqHz0CiE0ifJz963hynAk0xzbjcaPSqfbfwF41C

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Ubuntu 15.18-1.pgdg26.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: conta; Type: TABLE; Schema: public; Owner: eduardo
--

CREATE TABLE public.conta (
    dtype character varying(31) NOT NULL,
    id_conta bigint NOT NULL,
    balance numeric(10,2),
    titular character varying(255),
    emprestimo numeric(38,2),
    CONSTRAINT conta_dtype_check CHECK (((dtype)::text = ANY ((ARRAY['ContaCorrente'::character varying, 'ContaEmpresarial'::character varying, 'ContaPoupanca'::character varying])::text[])))
);


ALTER TABLE public.conta OWNER TO eduardo;

--
-- Name: conta_seq; Type: SEQUENCE; Schema: public; Owner: eduardo
--

CREATE SEQUENCE public.conta_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.conta_seq OWNER TO eduardo;

--
-- Name: transacao; Type: TABLE; Schema: public; Owner: eduardo
--

CREATE TABLE public.transacao (
    id bigint NOT NULL,
    data timestamp(6) with time zone,
    saldo_apos numeric(10,2),
    tipo_operacao character varying(255),
    valor numeric(10,2),
    id_conta bigint,
    CONSTRAINT transacao_tipo_operacao_check CHECK (((tipo_operacao)::text = ANY ((ARRAY['OPERACAO_DEPOSITO'::character varying, 'OPERACAO_SAQUE'::character varying, 'OPERACAO_TRANSFERENCIA'::character varying])::text[])))
);


ALTER TABLE public.transacao OWNER TO eduardo;

--
-- Name: transacao_id_seq; Type: SEQUENCE; Schema: public; Owner: eduardo
--

ALTER TABLE public.transacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conta conta_pkey; Type: CONSTRAINT; Schema: public; Owner: eduardo
--

ALTER TABLE ONLY public.conta
    ADD CONSTRAINT conta_pkey PRIMARY KEY (id_conta);


--
-- Name: transacao transacao_pkey; Type: CONSTRAINT; Schema: public; Owner: eduardo
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_pkey PRIMARY KEY (id);


--
-- Name: transacao fkj57iekb2ucoyifb1flof7kjml; Type: FK CONSTRAINT; Schema: public; Owner: eduardo
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT fkj57iekb2ucoyifb1flof7kjml FOREIGN KEY (id_conta) REFERENCES public.conta(id_conta);


--
-- PostgreSQL database dump complete
--

\unrestrict NL08lT4EKcPwTh2UqrsxVOGDrqHz0CiE0ifJz963hynAk0xzbjcaPSqfbfwF41C

