ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS razao_social VARCHAR(255);
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS cnpj VARCHAR(255);
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS agencia VARCHAR(255);
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS numero_conta VARCHAR(255);
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS limite_cheque_especial NUMERIC(10,2);
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS data_abertura DATE;
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS ativa BOOLEAN;
ALTER TABLE public.conta ADD COLUMN IF NOT EXISTS data_aniversario DATE;