ALTER TABLE conta ALTER COLUMN id_conta ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
       pg_get_serial_sequence('conta', 'id_conta'),
       COALESCE((SELECT MAX (id_conta)FROM conta), 1)
       )